version: '3.8'

services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skills_log
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./resource/sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  db_data:
