// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package skillslog

import (
	"database/sql"
)

type Member struct {
	ID        int32
	Name      string
	CreatedAt sql.NullTime
}

type MemberSkillRating struct {
	ID        int32
	MemberID  int32
	SkillID   int32
	Rating    int32
	CreatedAt sql.NullTime
}

type Skill struct {
	ID        int32
	Name      string
	CreatedAt sql.NullTime
}
