// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package skillslog

import (
	"context"
)

const createMember = `-- name: CreateMember :exec
INSERT INTO member (name) 
VALUES ($1)
`

func (q *Queries) CreateMember(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createMember)
	return err
}

const createSkill = `-- name: CreateSkill :exec
INSERT INTO skill (name) 
VALUES ($1)
`

func (q *Queries) CreateSkill(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createSkill)
	return err
}

const createSkillToMemberRating = `-- name: CreateSkillToMemberRating :exec
INSERT INTO member_skill_rating (member_id, skill_id, rating) 
VALUES ($1, $2, $3)
`

func (q *Queries) CreateSkillToMemberRating(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createSkillToMemberRating)
	return err
}
